# Generated by Django 5.0.1 on 2024-07-17 05:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SeekersInstitutes',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_mail_verified', models.BooleanField(default=False)),
                ('first_name', models.CharField(max_length=255)),
                ('phone_no', models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')])),
                ('is_institute', models.BooleanField(default=False)),
                ('institute_reg_number', models.CharField(blank=True, max_length=255, null=True)),
                ('given_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('institute_details', models.TextField(blank=True, null=True)),
                ('family_name', models.CharField(blank=True, max_length=255, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('picture', models.URLField(blank=True, null=True)),
                ('locale', models.CharField(blank=True, max_length=50, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('extra_field', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Speeches',
            fields=[
                ('speech_id', models.AutoField(primary_key=True, serialize=False)),
                ('speech_title', models.CharField(max_length=255)),
                ('speech_description', models.TextField()),
                ('is_picked', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('platform_url', models.URLField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speeches_created', to='social_connect_app.seekersinstitutes')),
            ],
        ),
        migrations.CreateModel(
            name='Wishes',
            fields=[
                ('wish_id', models.AutoField(primary_key=True, serialize=False)),
                ('wish_title', models.CharField(max_length=255)),
                ('wish_description', models.TextField()),
                ('is_picked', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishes_created', to='social_connect_app.seekersinstitutes')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('social_media_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.JSONField(blank=True, null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('platform', models.TextField(blank=True, null=True)),
                ('speech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to='social_connect_app.speeches')),
                ('wish', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_media_posts', to='social_connect_app.wishes')),
            ],
        ),
        migrations.CreateModel(
            name='SpeechStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='Created', max_length=20)),
                ('picked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_speech_statuses', to='social_connect_app.seekersinstitutes')),
                ('speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speech_statuses', to='social_connect_app.speeches')),
            ],
            options={
                'unique_together': {('speech', 'picked_by')},
            },
        ),
        migrations.CreateModel(
            name='WishStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Created', 'Created'), ('In-Progress', 'In-Progress'), ('Completed', 'Completed')], default='Created', max_length=20)),
                ('picked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picked_wish_statuses', to='social_connect_app.seekersinstitutes')),
                ('wish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wish_statuses', to='social_connect_app.wishes')),
            ],
            options={
                'unique_together': {('wish', 'picked_by')},
            },
        ),
    ]
