# Generated by Django 5.0.1 on 2024-07-17 13:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_connect_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="speechstatus",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="wishstatus",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="speechstatus",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="wishstatus",
            name="created_date",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="speechstatus",
            name="speech",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="speech_status",
                to="social_connect_app.speeches",
            ),
        ),
        migrations.AlterField(
            model_name="speechstatus",
            name="status",
            field=models.CharField(default="Created", max_length=50),
        ),
        migrations.AlterField(
            model_name="wishstatus",
            name="status",
            field=models.CharField(default="Created", max_length=50),
        ),
        migrations.AlterField(
            model_name="wishstatus",
            name="wish",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="wish_status",
                to="social_connect_app.wishes",
            ),
        ),
        migrations.CreateModel(
            name="CompletionDetails",
            fields=[
                ("completion_id", models.AutoField(primary_key=True, serialize=False)),
                ("completed_date", models.DateTimeField(auto_now_add=True)),
                (
                    "completed_by_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_connect_app.seekersinstitutes",
                    ),
                ),
                (
                    "speech",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_connect_app.speeches",
                    ),
                ),
                (
                    "wish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="social_connect_app.wishes",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "CompletionDetails",
            },
        ),
        migrations.RemoveField(
            model_name="speechstatus",
            name="picked_by",
        ),
        migrations.RemoveField(
            model_name="wishstatus",
            name="picked_by",
        ),
        migrations.AddField(
            model_name="speechstatus",
            name="picked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="picked_speech_statuses",
                to="social_connect_app.seekersinstitutes",
            ),
        ),
        migrations.AddField(
            model_name="wishstatus",
            name="picked_by",
            field=models.ManyToManyField(
                blank=True,
                related_name="picked_wish_statuses",
                to="social_connect_app.seekersinstitutes",
            ),
        ),
    ]
