# Generated by Django 5.0.1 on 2024-07-20 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_connect_app", "0002_alter_speechstatus_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialmedia",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="social_media_posts",
                to="social_connect_app.seekersinstitutes",
            ),
        ),
    ]
