# Generated by Django 5.0.1 on 2024-07-20 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("social_connect_app", "0003_socialmedia_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="speeches",
            name="selected_fulfillment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_speech",
                to="social_connect_app.socialmedia",
            ),
        ),
        migrations.AddField(
            model_name="wishes",
            name="selected_fulfillment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfilled_wish",
                to="social_connect_app.socialmedia",
            ),
        ),
        migrations.DeleteModel(
            name="CompletionDetails",
        ),
    ]
